/**********************************************************************************************************************
 * \file ButtonHandler.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef BUTTONHANDLER_H_
#define BUTTONHANDLER_H_

#include "Ifx_Types.h"
#include "IfxPort.h"
#include "MotorDriver.h"

/* 버튼 GPIO 핀 — 실제 배선에 맞게 수정 */
#define BTN_WIN_UP_PORT     &MODULE_P15
#define BTN_WIN_UP_PIN      15
#define BTN_WIN_DOWN_PORT   &MODULE_P15
#define BTN_WIN_DOWN_PIN    4
#define BTN_DOOR_PORT       &MODULE_P20
#define BTN_DOOR_PIN        14

/* 디바운스 시간 (ms) */
#define BTN_DEBOUNCE_MS     50u

void Button_Init(void);

/* 메인루프에서 매 주기 호출 */
void Button_Update(void);

#endif /* BUTTONHANDLER_H_ */
