/**********************************************************************************************************************
 * \file DoorApp.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef DOORAPP_H_
#define DOORAPP_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* =========================================================
 * Door ECU App Tunable Defines
 * 실제 HW 테스트하면서 조정할 값들
 * ========================================================= */

/* ---------- Motor ID ---------- */
#define DOOR_MOTOR_ID                   1U
#define WINDOW_MOTOR_ID                 2U

/* ---------- Handle Pressure (0x220) ---------- */
/* 손잡이 압력 이벤트 송신 시작 기준 (%)
 * FSR 노이즈와 손잡이 감도에 따라 실측 후 조정 */
#define HANDLE_PRESS_ACTIVE_TH          20U

/* 손잡이 압력 해제 기준 (%)
 * ACTIVE/RELEASE 히스테리시스를 줘서 임계점 근처 떨림 방지 */
#define HANDLE_PRESS_RELEASE_TH         20U

/* ---------- Button Debounce ---------- */
/* AppTask10ms 기준 3이면 약 30ms 디바운스 */
#define BUTTON_DEBOUNCE_COUNT           3U

/* ---------- Window Target Angle ---------- */
/* 현재 창문 모터를 각도 기반으로 단순 제어 중이므로
 * 추후 실제 스트로크 기준으로 바꿀 수 있음 */
#define WINDOW_OPEN_TARGET_ANGLE_DEG    90.0f
#define WINDOW_CLOSE_TARGET_ANGLE_DEG   0.0f

/* ---------- Pinch Recovery ---------- */
/* 끼임 감지 시 반대 방향으로 되돌릴 각도
 * 실제 테스트 시 가장 많이 조정할 가능성이 큰 값 */
#define DOOR_PINCH_RECOVERY_ANGLE_DEG   10.0f
#define WINDOW_PINCH_RECOVERY_ANGLE_DEG 10.0f

/* ---------- Door/Window Angle Limit ---------- */
#define DOOR_MIN_ANGLE_DEG              0.0f
#define DOOR_MAX_ANGLE_DEG              180.0f
#define WINDOW_MIN_ANGLE_DEG            0.0f
#define WINDOW_MAX_ANGLE_DEG            180.0f

/* ---------- Encoder to Angle ---------- */
/* 엔코더 카운트를 각도로 환산하는 비율
 * 반드시 실제 기구부 기준으로 보정 필요
 * 예시값이므로 완님 프로젝트 기준 count/deg로 수정 */
#define DOOR_ENCODER_COUNT_PER_DEG      1.0f
#define WINDOW_ENCODER_COUNT_PER_DEG    1.0f


#define OBSTACLE_THRESHOLD_CM   10U

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

void DoorLock_Init(void);

/* 추가: 스마트키 시퀀스 헬퍼 */
void DoorSmartKeyUnlockSequence(void);
void DoorSmartKeyLockSequence(void);

float clampFloat32(float value, float minVal, float maxVal);

void DoorButton_Task(void);
void WindowButton_Task(void);
void DoorControl_Task(void);
void UserSetting_Task(void);


#endif /* DOORAPP_H_ */
