/**********************************************************************************************************************
 * \file RGB_LED.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "RGB_LED.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* Global */
#define PCn_0_IDX 3
#define PCn_4_IDX 3
#define PCn_5_IDX 11

#define PCx_GENERAL_OUTPUT  0x10

/* RGB LED */
#define RGB_RED_PIN     0
#define RGB_GREEN_PIN   4
#define RGB_BLUE_PIN    5

#define RGB_OUT_PCx (PCx_GENERAL_OUTPUT)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

typedef struct
{
    uint8 red;
    uint8 green;
    uint8 blue;
} RGBState;

RGBState rgbState;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

void RGB_Reset(void);
void turnRGBOn(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* RGB LED Task */

void RGB_Task(void)
{
    static uint8 colorIdx = 0;

    RGB_Reset();

    switch(colorIdx)
    {
        case 0:
            rgbState.red = 1;
            break;

        case 1:
            rgbState.green = 1;
            break;

        case 2:
            rgbState.blue = 1;
            break;

        default:
            colorIdx = 0;
            rgbState.red = 1;
            break;
    }

    turnRGBOn();

    colorIdx++;
    if(colorIdx >= 3)
    {
        colorIdx = 0;
    }
}

/****************/

/* RGB LED Init */

void initRGB(void)
{
    // set RED pin
    P02_IOCR0.U &= ~(0x1F << PCn_0_IDX);
    P02_IOCR0.U |=  (RGB_OUT_PCx << PCn_0_IDX);

    // set GREEN pin
    P10_IOCR4.U &= ~(0x1F << PCn_4_IDX);
    P10_IOCR4.U |=  (RGB_OUT_PCx << PCn_4_IDX);

    // set BLUE pin
    P10_IOCR4.U &= ~(0x1F << PCn_5_IDX);
    P10_IOCR4.U |=  (RGB_OUT_PCx << PCn_5_IDX);
}

/*******************/

/* RGB LED Library */

void RGB_Reset(void)
{
    rgbState.red = 0;
    rgbState.green = 0;
    rgbState.blue = 0;

    P02_OUT.U &= ~(1U << RGB_RED_PIN);
    P10_OUT.U &= ~(1U << RGB_GREEN_PIN);
    P10_OUT.U &= ~(1U << RGB_BLUE_PIN);
}

void turnRGBOn(void)
{
    if (rgbState.red)
        P02_OUT.U |=  (1U << RGB_RED_PIN);

    if (rgbState.green)
        P10_OUT.U |=  (1U << RGB_GREEN_PIN);

    if (rgbState.blue)
        P10_OUT.U |=  (1U << RGB_BLUE_PIN);
}

