/**********************************************************************************************************************
 * \file BT.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include <string.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define BT_BAUDRATE             9600
#define BT_TX_BUFFER_SIZE       128
#define BT_RX_BUFFER_SIZE       128

// 예시 핀: 실제 보드 핀맵에 맞게 수정 필요
#define BT_PIN_RX               IfxAsclin0_RXB_P15_3_IN
#define BT_PIN_TX               IfxAsclin0_TX_P15_2_OUT

/* Definition of the interrupt priorities */
#define INTPRIO_ASCLIN0_RX      22
#define INTPRIO_ASCLIN0_TX      23

#define UART_RX_BUFFER_SIZE     64                                      /* Definition of the receive buffer size    */
#define UART_TX_BUFFER_SIZE     64                                      /* Definition of the transmit buffer size   */
#define SIZE                    13                                      /* Size of the string                       */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Declaration of the ASC handle */
static IfxAsclin_Asc g_btAsc;

/* Declaration of the FIFOs parameters */
static uint8 g_btTxBuffer[BT_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_btRxBuffer[BT_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

static uint8 g_btRxRing[128];
static volatile uint16 g_btRxWrite = 0;
static volatile uint16 g_btRxRead  = 0;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

boolean BT_ReadByte(uint8 *ch);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Interrupt Service Routines */
IFX_INTERRUPT(asclin0TxISR, 0, INTPRIO_ASCLIN0_TX);
void asclin0TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_btAsc);
}

IFX_INTERRUPT(asclin0RxISR, 0, INTPRIO_ASCLIN0_RX);
void asclin0RxISR(void)
{
    IfxAsclin_Asc_isrReceive(&g_btAsc);
}

/***********/

/* BT Task */

volatile uint32 g_btRxByteCount = 0;
volatile uint8  g_btLastRxByte = 0;
volatile uint32 g_btRxOverflowCount = 0;

void BT_Task(void)
{
    uint8 ch;
    uint16 count = 0;

    while (BT_ReadByte(&ch))
    {
        g_btLastRxByte = ch;
        g_btRxByteCount++;

        uint16 next = (g_btRxWrite + 1) % sizeof(g_btRxRing);
        if (next != g_btRxRead)
        {
            g_btRxRing[g_btRxWrite] = ch;
            g_btRxWrite = next;
        }
        else
        {
            g_btRxOverflowCount++;
            break;
        }

        count++;
        if (count >= 64)
        {
            break;
        }
    }
}

/***********/

/* BT Init */

/* This function initializes the ASCLIN UART module */
void init_ASCLIN0_UART(void)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN0);

    /* Set the desired baud rate */
    ascConfig.baudrate.baudrate = BT_BAUDRATE;

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN0_TX;
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN0_RX;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig.txBuffer = &g_btTxBuffer;
    ascConfig.txBufferSize = BT_TX_BUFFER_SIZE;
    ascConfig.rxBuffer = &g_btRxBuffer;
    ascConfig.rxBufferSize = BT_RX_BUFFER_SIZE;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR,       IfxPort_InputMode_pullUp,     /* CTS pin not used */
        &BT_PIN_RX,   IfxPort_InputMode_pullUp,       /* RX pin           */
        NULL_PTR,       IfxPort_OutputMode_pushPull,  /* RTS pin not used */
        &BT_PIN_TX,   IfxPort_OutputMode_pushPull,    /* TX pin           */
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_btAsc, &ascConfig); /* Initialize module with above parameters */
}

void initBT(void) {
    init_ASCLIN0_UART();
}

/**************/

/* BT Library */

void BT_SendBytes(const uint8 *data, Ifx_SizeT len)
{
    Ifx_SizeT count = len;
    IfxAsclin_Asc_write(&g_btAsc, (void *)data, &count, TIME_INFINITE);
}

void BT_SendString(const char *str)
{
    Ifx_SizeT count = strlen(str);
    IfxAsclin_Asc_write(&g_btAsc, (void *)str, &count, TIME_INFINITE);
}

boolean BT_ReadByte(uint8 *ch)
{
    Ifx_SizeT count = 1;
    IfxAsclin_Asc_read(&g_btAsc, ch, &count, 1);

    return (count == 1) ? TRUE : FALSE;
}

boolean BT_GetChar(uint8 *ch)
{
    if (g_btRxRead == g_btRxWrite)
    {
        return FALSE;
    }

    *ch = g_btRxRing[g_btRxRead];
    g_btRxRead = (g_btRxRead + 1) % sizeof(g_btRxRing);
    return TRUE;
}
