/**********************************************************************************************************************
 * \file BT.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "BT.h"
#include <string.h>
#include "MCMCAN.h"
#include "DoorApp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define BT_BAUDRATE             9600
#define BT_TX_BUFFER_SIZE       128
#define BT_RX_BUFFER_SIZE       128

// 예시 핀: 실제 보드 핀맵에 맞게 수정 필요
#define BT_PIN_RX               IfxAsclin0_RXB_P15_3_IN
#define BT_PIN_TX               IfxAsclin0_TX_P15_2_OUT

/* Definition of the interrupt priorities */
#define INTPRIO_ASCLIN0_RX      22
#define INTPRIO_ASCLIN0_TX      23

#define UART_RX_BUFFER_SIZE     64                                      /* Definition of the receive buffer size    */
#define UART_TX_BUFFER_SIZE     64                                      /* Definition of the transmit buffer size   */
#define SIZE                    13                                      /* Size of the string                       */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Declaration of the ASC handle */
static IfxAsclin_Asc g_btAsc;

/* Declaration of the FIFOs parameters */
static uint8 g_btTxBuffer[BT_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_btRxBuffer[BT_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

static uint8 g_btRxRing[128];
static volatile uint16 g_btRxWrite = 0;
static volatile uint16 g_btRxRead  = 0;

/* line buffer */
static volatile uint8 g_btLine[64];
static volatile uint8 g_btWorkLine[64];
static volatile boolean g_btLineReady = FALSE;

/* BT state */
static volatile UserId_t g_btSelectedUser = USER_ID_1;
static volatile boolean g_btNearby = FALSE;

/* debug */
volatile uint32 g_btRxByteCount = 0;
volatile uint8  g_btLastRxByte = 0;
volatile uint32 g_btRxOverflowCount = 0;

volatile uint32 g_dbgBtCmdCnt = 0U;
volatile uint32 g_dbgBtCmdErrCnt = 0U;
volatile BtnType_t g_dbgBtLastBtnType = (BtnType_t)0xFFU;
volatile UserId_t g_dbgBtLastUser = USER_ID_1;
volatile BtCommandType_t g_dbgBtLastCmdType = BT_CMD_NONE;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

static boolean BT_ParseUserId(const char *line, UserId_t *userId, const char **cmdStr);
static BtCommandType_t BT_ParseCommandType(const char *cmdStr);
static void BT_HandleParsedCommand(const BtParsedCommand_t *cmd);
static void BT_HandleButtonCommand(UserId_t userId, BtnType_t btnType);
static void BT_HandleProximityCommand(UserId_t userId, BtCommandType_t cmdType);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Interrupt Service Routines */
IFX_INTERRUPT(asclin0TxISR, 0, INTPRIO_ASCLIN0_TX);
void asclin0TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_btAsc);
}

IFX_INTERRUPT(asclin0RxISR, 0, INTPRIO_ASCLIN0_RX);
void asclin0RxISR(void)
{
    IfxAsclin_Asc_isrReceive(&g_btAsc);
}

/***********/

/* BT Task */

void BT_Task(void)
{
    uint8 ch;
    uint16 count = 0;

    while (BT_ReadByte(&ch))
    {
        g_btLastRxByte = ch;
        g_btRxByteCount++;

        {
            uint16 next = (uint16)((g_btRxWrite + 1U) % sizeof(g_btRxRing));
            if (next != g_btRxRead)
            {
                g_btRxRing[g_btRxWrite] = ch;
                g_btRxWrite = next;
            }
            else
            {
                g_btRxOverflowCount++;
                break;
            }
        }

        count++;
        if (count >= 64U)
        {
            break;
        }
    }
}

void BT_LineTask(void)
{
    static uint8 idx = 0U;
    uint8 ch;

    while (BT_GetChar(&ch))
    {
        if ((ch != '\r') && (ch != '\n'))
        {
            if (idx < (sizeof(g_btWorkLine) - 1U))
            {
                g_btWorkLine[idx++] = ch;
            }
        }

        if ((ch == '\r') || (ch == '\n'))
        {
            if (idx > 0U)
            {
                g_btWorkLine[idx] = '\0';
                strcpy((char *)g_btLine, (char *)g_btWorkLine);
                g_btLineReady = TRUE;
                idx = 0U;
            }
        }
    }
}

/*****************/
/* BT Parse Task */
/*****************/
static boolean BT_ParseUserId(const char *line, UserId_t *userId, const char **cmdStr)
{
    const char *colonPos;

    if ((line == NULL) || (userId == NULL) || (cmdStr == NULL))
    {
        return FALSE;
    }

    if (line[0] != 'U')
    {
        return FALSE;
    }

    colonPos = strchr(line, ':');
    if (colonPos == NULL)
    {
        return FALSE;
    }

    if (line[1] == '0')
    {
        *userId = USER_ID_1;   /* 0x00 */
    }
    else if (line[1] == '1')
    {
        *userId = USER_ID_2;   /* 0x01 */
    }
    else if (line[1] == '2')
    {
        *userId = USER_ID_3;   /* 0x02 */
    }
    else
    {
        return FALSE;
    }

    *cmdStr = colonPos + 1;

    if (**cmdStr == '\0')
    {
        return FALSE;
    }

    return TRUE;
}

static BtCommandType_t BT_ParseCommandType(const char *cmdStr)
{
    if (cmdStr == NULL) return BT_CMD_NONE;

    if (strcmp(cmdStr, "RSSI_NEAR") == 0)   return BT_CMD_RSSI_NEAR;
    if (strcmp(cmdStr, "RSSI_FAR") == 0)    return BT_CMD_RSSI_FAR;
    if (strcmp(cmdStr, "LOCK") == 0)        return BT_CMD_LOCK;
    if (strcmp(cmdStr, "UNLOCK") == 0)      return BT_CMD_UNLOCK;
    if (strcmp(cmdStr, "WINDOW_OPEN") == 0) return BT_CMD_WINDOW_OPEN;
    if (strcmp(cmdStr, "WINDOW_CLOSE") == 0)return BT_CMD_WINDOW_CLOSE;
    if (strcmp(cmdStr, "FORWARD") == 0)     return BT_CMD_FORWARD;
    if (strcmp(cmdStr, "BACKWARD") == 0)    return BT_CMD_BACKWARD;

    return BT_CMD_NONE;
}

BtParsedCommand_t BT_ParseLine(const char *line)
{
    BtParsedCommand_t parsed;
    const char *cmdStr = NULL;

    parsed.valid = FALSE;
    parsed.userId = USER_ID_1;
    parsed.cmdType = BT_CMD_NONE;

    if (BT_ParseUserId(line, &parsed.userId, &cmdStr) == FALSE)
    {
        return parsed;
    }

    parsed.cmdType = BT_ParseCommandType(cmdStr);
    if (parsed.cmdType == BT_CMD_NONE)
    {
        return parsed;
    }

    parsed.valid = TRUE;
    return parsed;
}

static void BT_HandleButtonCommand(UserId_t userId, BtnType_t btnType)
{
    g_dbgBtLastUser = userId;
    g_dbgBtLastBtnType = btnType;

    /* 로컬 즉시 반영은 선택 */
    switch (btnType)
    {
        case BTN_TYPE_LOCK:
            g_ctrlState.lock_state = LOCK_CMD_LOCK;
            break;

        case BTN_TYPE_UNLOCK:
            g_ctrlState.lock_state = LOCK_CMD_UNLOCK;
            break;

        case BTN_TYPE_WINDOW_OPEN:
            g_ctrlState.window_state = OPEN_CLOSE_OPEN;
            break;

        case BTN_TYPE_WINDOW_CLOSE:
            g_ctrlState.window_state = OPEN_CLOSE_CLOSE;
            break;

        case BTN_TYPE_FORWARD:
        case BTN_TYPE_REVERSE:
        default:
            break;
    }

    /* 실제 0x210 송신: B0=user_id, B1=btn_type */
    can_send_SmtkButtonBypass(userId, btnType);
}

static void BT_HandleProximityCommand(UserId_t userId, BtCommandType_t cmdType)
{
    g_dbgBtLastUser = userId;

    switch (cmdType)
    {
        case BT_CMD_RSSI_NEAR:
            g_btNearby = TRUE;
            can_send_SmtkRssiEvent(userId, RSSI_TYPE_NEAR);
            break;

        case BT_CMD_RSSI_FAR:
            g_btNearby = FALSE;
            can_send_SmtkRssiEvent(userId, RSSI_TYPE_FAR);
            break;

        default:
            break;
    }
}

static void BT_HandleParsedCommand(const BtParsedCommand_t *cmd)
{
    if ((cmd == NULL) || (cmd->valid == FALSE))
    {
        g_dbgBtCmdErrCnt++;
        return;
    }

    g_dbgBtCmdCnt++;
    g_dbgBtLastCmdType = cmd->cmdType;

    switch (cmd->cmdType)
    {
        case BT_CMD_LOCK:
            BT_HandleButtonCommand(cmd->userId, BTN_TYPE_LOCK);
            break;

        case BT_CMD_UNLOCK:
            BT_HandleButtonCommand(cmd->userId, BTN_TYPE_UNLOCK);
            break;

        case BT_CMD_WINDOW_OPEN:
            BT_HandleButtonCommand(cmd->userId, BTN_TYPE_WINDOW_OPEN);
            break;

        case BT_CMD_WINDOW_CLOSE:
            BT_HandleButtonCommand(cmd->userId, BTN_TYPE_WINDOW_CLOSE);
            break;

        case BT_CMD_FORWARD:
            BT_HandleButtonCommand(cmd->userId, BTN_TYPE_FORWARD);
            break;

        case BT_CMD_BACKWARD:
            BT_HandleButtonCommand(cmd->userId, BTN_TYPE_REVERSE);
            break;

        case BT_CMD_RSSI_NEAR:
        case BT_CMD_RSSI_FAR:
            BT_HandleProximityCommand(cmd->userId, cmd->cmdType);
            break;

        default:
            g_dbgBtCmdErrCnt++;
            break;
    }
}

void BT_ProcessTask(void)
{
    BtParsedCommand_t cmd;

    BT_LineTask();

    if (g_btLineReady == TRUE)
    {
        g_btLineReady = FALSE;
        cmd = BT_ParseLine((const char *)g_btLine);
        BT_HandleParsedCommand(&cmd);
    }
}

/***********/

/* BT Init */

/* This function initializes the ASCLIN UART module */
void init_ASCLIN0_UART(void)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN0);

    /* Set the desired baud rate */
    ascConfig.baudrate.baudrate = BT_BAUDRATE;

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN0_TX;
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN0_RX;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig.txBuffer = &g_btTxBuffer;
    ascConfig.txBufferSize = BT_TX_BUFFER_SIZE;
    ascConfig.rxBuffer = &g_btRxBuffer;
    ascConfig.rxBufferSize = BT_RX_BUFFER_SIZE;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR,       IfxPort_InputMode_pullUp,     /* CTS pin not used */
        &BT_PIN_RX,   IfxPort_InputMode_pullUp,       /* RX pin           */
        NULL_PTR,       IfxPort_OutputMode_pushPull,  /* RTS pin not used */
        &BT_PIN_TX,   IfxPort_OutputMode_pushPull,    /* TX pin           */
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_btAsc, &ascConfig); /* Initialize module with above parameters */
}

void initBT(void) {
    init_ASCLIN0_UART();
}

/**************/

/* BT Library */

void BT_SendBytes(const uint8 *data, Ifx_SizeT len)
{
    Ifx_SizeT count = len;
    IfxAsclin_Asc_write(&g_btAsc, (void *)data, &count, TIME_INFINITE);
}

void BT_SendString(const char *str)
{
    Ifx_SizeT count = strlen(str);
    IfxAsclin_Asc_write(&g_btAsc, (void *)str, &count, TIME_INFINITE);
}

boolean BT_ReadByte(uint8 *ch)
{
    Ifx_SizeT count = 1;
    IfxAsclin_Asc_read(&g_btAsc, ch, &count, 1);
    return (count == 1) ? TRUE : FALSE;
}

boolean BT_GetChar(uint8 *ch)
{
    if (g_btRxRead == g_btRxWrite)
    {
        return FALSE;
    }

    *ch = g_btRxRing[g_btRxRead];
    g_btRxRead = (uint16)((g_btRxRead + 1U) % sizeof(g_btRxRing));
    return TRUE;
}

UserId_t BT_GetSelectedUser(void)
{
    return g_btSelectedUser;
}

boolean BT_IsNearby(void)
{
    return g_btNearby;
}
