/**********************************************************************************************************************
 * \file BT.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#ifndef BT_H_
#define BT_H_

#include "Ifx_Types.h"
#include "can_type_def.h"

/*********************************************************************************************************************/
/*------------------------------------------------Type Definitions---------------------------------------------------*/
/*********************************************************************************************************************/
typedef enum
{
    BT_CMD_NONE = 0,
    BT_CMD_RSSI_NEAR,
    BT_CMD_RSSI_FAR,
    BT_CMD_LOCK,
    BT_CMD_UNLOCK,
    BT_CMD_WINDOW_OPEN,
    BT_CMD_WINDOW_CLOSE,
    BT_CMD_FORWARD,
    BT_CMD_BACKWARD
} BtCommandType_t;

typedef struct
{
    boolean         valid;
    UserId_t        userId;
    BtCommandType_t cmdType;
} BtParsedCommand_t;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initBT(void);
void BT_SendBytes(const uint8 *data, Ifx_SizeT len);
void BT_SendString(const char *str);
boolean BT_ReadByte(uint8 *ch);
void BT_Task(void);
boolean BT_GetChar(uint8 *ch);

/* line parse/process */
void BT_LineTask(void);
BtParsedCommand_t BT_ParseLine(const char *line);
void BT_ProcessTask(void);

/* state */
UserId_t BT_GetSelectedUser(void);
boolean BT_IsNearby(void);

extern volatile uint32 g_dbgBtCmdCnt;
extern volatile uint32 g_dbgBtCmdErrCnt;
extern volatile BtnType_t g_dbgBtLastBtnType;
extern volatile UserId_t g_dbgBtLastUser;
extern volatile BtCommandType_t g_dbgBtLastCmdType;

#endif /* BT_H_ */
