/**********************************************************************************************************************
 * \file Buzzer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <Buzzer.h>
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"
#include "MCMCAN.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_TOM    20                                      /* Interrupt priority number                    */
#define PWM_PERIOD          50000                                   /* PWM period for the TOM                       */

/* BUZZER */
#define BUZ_PIN         3

#define BUZ_PWM_TOM_OUT     IfxGtm_TOM0_11_TOUT3_P02_3_OUT

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

IfxGtm_Tom_Pwm_Driver g_buzzerTomDriver;
IfxGtm_Tom_Pwm_Config g_buzzerTomConfig;

volatile BuzEvent_t g_buzReqEvent = BUZ_EVENT_NONE;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/
void setDutyCycle(uint32 dutyCycle);                                /* Function to set the duty cycle of the PWM    */

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/

/* 내부 상태 */
typedef struct
{
    boolean    active;
    BuzEvent_t currentEvent;
    uint16     stepTick;
    uint8      step;
} BuzPatternState_t;

static BuzPatternState_t g_buzState = { FALSE, BUZ_EVENT_NONE, 0, 0 };

/* BUZZER Task */

/* 10ms 주기 호출 기준 */
void BUZ_Task(void)
{
    /* 새 이벤트 들어오면 패턴 시작 */
    if (g_buzReqEvent != BUZ_EVENT_NONE)
    {
        g_buzState.active       = TRUE;
        g_buzState.currentEvent = g_buzReqEvent;
        g_buzState.step         = 0;
        g_buzState.stepTick     = 0;
        g_buzReqEvent           = BUZ_EVENT_NONE;
        Buzzer_Off();
    }

    if (g_buzState.active == FALSE)
    {
        return;
    }

    g_buzState.stepTick++;

    switch (g_buzState.currentEvent)
    {
        /* 0x103 장애물 감지: 짧게 2번 삑삑 */
        case BUZ_EVENT_OBSTACLE:
            switch (g_buzState.step)
            {
                case 0:
                    makeSound(9); /* A4 */
                    if (g_buzState.stepTick >= 10)   /* 100ms */
                    {
                        Buzzer_Off();
                        g_buzState.step = 1;
                        g_buzState.stepTick = 0;
                    }
                    break;

                case 1:
                    if (g_buzState.stepTick >= 5)    /* 50ms 쉼 */
                    {
                        g_buzState.step = 2;
                        g_buzState.stepTick = 0;
                    }
                    break;

                case 2:
                    makeSound(9);
                    if (g_buzState.stepTick >= 10)   /* 100ms */
                    {
                        Buzzer_Off();
                        g_buzState.active = FALSE;
                        g_buzState.currentEvent = BUZ_EVENT_NONE;
                    }
                    break;

                default:
                    g_buzState.active = FALSE;
                    Buzzer_Off();
                    break;
            }
            break;

        /* 0x143 안전 하차 보조: 조금 더 길고 급한 경고음 */
        case BUZ_EVENT_SAFE_EXIT:
            switch (g_buzState.step)
            {
                case 0:
                    makeSound(11); /* B4 */
                    if (g_buzState.stepTick >= 20)   /* 200ms */
                    {
                        Buzzer_Off();
                        g_buzState.step = 1;
                        g_buzState.stepTick = 0;
                    }
                    break;

                case 1:
                    if (g_buzState.stepTick >= 5)    /* 50ms */
                    {
                        g_buzState.step = 2;
                        g_buzState.stepTick = 0;
                    }
                    break;

                case 2:
                    makeSound(12); /* C5 */
                    if (g_buzState.stepTick >= 20)   /* 200ms */
                    {
                        Buzzer_Off();
                        g_buzState.active = FALSE;
                        g_buzState.currentEvent = BUZ_EVENT_NONE;
                    }
                    break;

                default:
                    g_buzState.active = FALSE;
                    Buzzer_Off();
                    break;
            }
            break;

        /* 0x104 도난 감지: 반복 경보 느낌 */
        case BUZ_EVENT_THEFT:
            switch (g_buzState.step)
            {
                case 0:
                    makeSound(12); /* C5 */
                    if (g_buzState.stepTick >= 15)   /* 150ms */
                    {
                        Buzzer_Off();
                        g_buzState.step = 1;
                        g_buzState.stepTick = 0;
                    }
                    break;

                case 1:
                    if (g_buzState.stepTick >= 5)    /* 50ms */
                    {
                        g_buzState.step = 2;
                        g_buzState.stepTick = 0;
                    }
                    break;

                case 2:
                    makeSound(12);
                    if (g_buzState.stepTick >= 15)
                    {
                        Buzzer_Off();
                        g_buzState.step = 3;
                        g_buzState.stepTick = 0;
                    }
                    break;

                case 3:
                    if (g_buzState.stepTick >= 5)
                    {
                        g_buzState.step = 4;
                        g_buzState.stepTick = 0;
                    }
                    break;

                case 4:
                    makeSound(12);
                    if (g_buzState.stepTick >= 15)
                    {
                        Buzzer_Off();
                        g_buzState.active = FALSE;
                        g_buzState.currentEvent = BUZ_EVENT_NONE;
                    }
                    break;

                default:
                    g_buzState.active = FALSE;
                    Buzzer_Off();
                    break;
            }
            break;

            /* 끼임 감지: 짧고 빠르게 3번 */
            case BUZ_EVENT_PINCH:
                switch (g_buzState.step)
                {
                    case 0:
                        makeSound(12); /* C5 */
                        if (g_buzState.stepTick >= 8)   /* 80ms */
                        {
                            Buzzer_Off();
                            g_buzState.step = 1;
                            g_buzState.stepTick = 0;
                        }
                        break;

                    case 1:
                        if (g_buzState.stepTick >= 3)   /* 30ms 쉼 */
                        {
                            g_buzState.step = 2;
                            g_buzState.stepTick = 0;
                        }
                        break;

                    case 2:
                        makeSound(12);
                        if (g_buzState.stepTick >= 8)
                        {
                            Buzzer_Off();
                            g_buzState.step = 3;
                            g_buzState.stepTick = 0;
                        }
                        break;

                    case 3:
                        if (g_buzState.stepTick >= 3)
                        {
                            g_buzState.step = 4;
                            g_buzState.stepTick = 0;
                        }
                        break;

                    case 4:
                        makeSound(12);
                        if (g_buzState.stepTick >= 8)
                        {
                            Buzzer_Off();
                            g_buzState.active = FALSE;
                            g_buzState.currentEvent = BUZ_EVENT_NONE;
                        }
                        break;

                    default:
                        g_buzState.active = FALSE;
                        Buzzer_Off();
                        break;
                }
                break;

        default:
            g_buzState.active = FALSE;
            g_buzState.currentEvent = BUZ_EVENT_NONE;
            Buzzer_Off();
            break;
    }
}

void Buzzer_Request(BuzEvent_t event)
{
    g_buzReqEvent = event;
}

/* BUZZER Init */

/* This function initializes the TOM */
void initGtmTomPwm(void)
{
    IfxGtm_enable(&MODULE_GTM);                                     /* Enable GTM                                   */

    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);   /* Enable the FXU clock                         */

    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&g_buzzerTomConfig, &MODULE_GTM);

    g_buzzerTomConfig.tom = BUZ_PWM_TOM_OUT.tom;                                /* Select the TOM                           */
    g_buzzerTomConfig.tomChannel = BUZ_PWM_TOM_OUT.channel;                     /* Select the channel                       */
    g_buzzerTomConfig.period = PWM_PERIOD;                                      /* Set timer period                         */
    g_buzzerTomConfig.dutyCycle = PWM_PERIOD/2;                                 /* Set the duty cycle                       */
    g_buzzerTomConfig.pin.outputPin = &BUZ_PWM_TOM_OUT;                         /* Set the pin as output                    */
    g_buzzerTomConfig.synchronousUpdateEnabled = TRUE;                          /* Enable synchronous update                */
    g_buzzerTomConfig.clock = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk1;                   /* Select the FXU clock 1                   */

    IfxGtm_Tom_Pwm_init(&g_buzzerTomDriver, &g_buzzerTomConfig);                /* Initialize the module                    */
    // IfxGtm_Tom_Pwm_start(&g_buzzerTomDriver, TRUE);                             /* Start the generation of the PWM signal   */
}

void initBUZ(void)
{
    initGtmTomPwm();
}

/******************/

/* BUZZER Library */

void Buzzer_On(void)
{
    IfxGtm_Tom_Pwm_start(&g_buzzerTomDriver, TRUE);
}

void Buzzer_Off(void)
{
    IfxGtm_Tom_Pwm_stop(&g_buzzerTomDriver, TRUE);
}

void makeSound(unsigned int sound)
{
    uint32 uPeriod = 0;
     float fBuzz[14] = {
        261.63, // 0: 도 (C4)
        277.18, // 1: 도# (C#4)
        293.66, // 2: 레 (D4)
        311.13, // 3: 레# (D#4)
        329.63, // 4: 미 (E4)
        349.23, // 5: 파 (F4)
        369.99, // 6: 파# (F#4)
        392.00, // 7: 솔 (G4)
        415.30, // 8: 솔# (G#4)
        440.00, // 9: 라 (A4)
        466.16, // 10: 라# (A#4)
        493.88, // 11: 시 (B4)
        523.25, // 12: 도 (C5)
        554.37  // 13: 도# (C#5)
     };

     uPeriod = (uint32)(625000.0f/fBuzz[sound]);

     IfxGtm_Tom_Pwm_stop(&g_buzzerTomDriver, TRUE);

     g_buzzerTomConfig.period = uPeriod;
     g_buzzerTomConfig.dutyCycle = (uint16)(uPeriod*0.3f);

     IfxGtm_Tom_Pwm_init(&g_buzzerTomDriver, &g_buzzerTomConfig);
     IfxGtm_Tom_Pwm_start(&g_buzzerTomDriver, TRUE);
}

void stopSound(void)
{
    unsigned short uDuty = 0;

    setDutyCycle(uDuty);
}

/* This function sets the duty cycle of the PWM */
void setDutyCycle(uint32 dutyCycle)
{
    g_buzzerTomConfig.dutyCycle = dutyCycle;                              /* Change the value of the duty cycle           */
    IfxGtm_Tom_Pwm_init(&g_buzzerTomDriver, &g_buzzerTomConfig);          /* Re-initialize the PWM                        */
}

