/**********************************************************************************************************************
 * \file Current_Sensor.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Current_Sensor.h"
#include "IfxCpu_Irq.h"
#include "IfxEvadc_Adc.h"
#include "EVADC_Manager.h"
#include "MCMCAN.h"
#include "IfxSrc.h"
#include "DoorApp.h"
#include <math.h>
#include "Buzzer.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* AN1 = Group0 Channel1, AN2 = Group0 Channel2 */
#define DOOR_CHANNEL_ID         IfxEvadc_ChannelId_1
#define DOOR_RESULT_REG         IfxEvadc_ChannelResult_1

#define WINDOW_CHANNEL_ID       IfxEvadc_ChannelId_2
#define WINDOW_RESULT_REG       IfxEvadc_ChannelResult_2

#define CUR_REF_VOLTAGE         5.0f
#define CUR_ADC_MAX             4095.0f

/* ACS712 설정 */
#define ACS_ZERO_VOLT_DEFAULT   2.5f
#define ACS_SENSITIVITY         0.1f        /* 20A 버전 : 100mV/A */

/* MOTER ID */
#define DOOR_MOTOR_ID   1
#define WINDOW_MOTOR_ID 2

/* DOOR 감시 파라미터 (RAW 기준) */
#define DOOR_FILTER_ALPHA           0.2f
#define DOOR_START_BLANK_COUNT      8         /* 10ms task 기준 약 80ms */
#define DOOR_BASELINE_SAMPLES       20
#define DOOR_JAM_RAW_DIFF_TH        18000.0f    // 끼임 후보
#define DOOR_JAM_COUNT_TH           3

/* WINDOW 감시 파라미터 (RAW 기준) */
#define WINDOW_FILTER_ALPHA         0.2f
#define WINDOW_START_BLANK_COUNT    8         /* 10ms task 기준 약 80ms */
#define WINDOW_BASELINE_SAMPLES     20
#define WINDOW_JAM_RAW_DIFF_TH      220000.0f    // 끼임 후보
#define WINDOW_JAM_COUNT_TH         3

/* 인터럽트 */
#define DOOR_ISR_PRIORITY       5
#define WINDOW_ISR_PRIORITY     6
#define CUR_ISR_PROVIDER        IfxSrc_Tos_cpu0

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/* EVADC handle */
static IfxEvadc_Adc_Channel g_curDoorChannel;
static IfxEvadc_Adc_Channel g_curWindowChannel;

/* Current Sensor Value */
typedef struct
{
    /* ADC result / converted value */
    volatile uint16  curRaw;
    volatile float32 curVolt;
    volatile float32 curAmp;

    /* state */
    volatile boolean spike;
    volatile boolean curValid;

    /* jam detection */
    volatile uint8   jamCnt;
    volatile float32 filtRaw;
    volatile float32 baseRaw;
    volatile float32 diffRaw;
    volatile float32 peakDiffRaw;

    /* sensing flow */
    volatile boolean senseActive;
    volatile boolean monitoring;
    volatile boolean faultLatched;

    volatile uint16  blankCnt;
    volatile uint16  baseCnt;

    /* sensor calibration */
    volatile float32 zeroVolt;

    /* fault */
    volatile CurrentFaultType fault;
} CurrentSensorState;

static CurrentSensorState g_doorSensor =
{
    .zeroVolt = ACS_ZERO_VOLT_DEFAULT,
    .fault    = CURRENT_FAULT_NONE
};

static CurrentSensorState g_windowSensor =
{
    .zeroVolt = ACS_ZERO_VOLT_DEFAULT,
    .fault    = CURRENT_FAULT_NONE
};

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

static float32 Current_CalcAmp(float32 voltage, float32 zeroVolt);
static CurrentSensorState* getCurrentSensor(uint8 motorId);

void CurrentSensor_StartSense(uint8 motorId);
void CurrentSensor_StopSense(uint8 motorId);

void CurrentSensor_ClearFault(uint8 motorId);
CurrentFaultType CurrentSensor_GetFault(uint8 motorId);
uint16 CurrentSensor_GetRaw(uint8 motorId);
float32 CurrentSensor_GetAmp(uint8 motorId);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Task */
void PinchMonitor_Task(void)
{
    CurrentFaultType doorFault;
    CurrentFaultType windowFault;
    float32 currentAngle;
    float32 recoveryTarget;

    doorFault = CurrentSensor_GetFault(DOOR_MOTOR_ID);
    windowFault = CurrentSensor_GetFault(WINDOW_MOTOR_ID);

    /* -------------------------------------------------
     * Door pinch
     * ------------------------------------------------- */
    if (doorFault == CURRENT_FAULT_MOTOR)
    {
        /* 즉시 정지 */
        Door_Motor_Stop();

        /* 전류 감시 중지 */
        CurrentSensor_StopSense(DOOR_MOTOR_ID);

        /* CAN 알림 */
        can_send_PinchDetection(PINCH_TYPE_DOOR);

        /* 버저 경고 */
        Buzzer_Request(BUZ_EVENT_PINCH);

        /* 현재 각도 기준 반대 방향 10도 복귀 */
        currentAngle = Door_Motor_GetCurrentAngle();

        if (g_rxDoorOpenCmd == OPEN_CLOSE_CLOSE)
        {
            /* 닫히는 중 끼임 -> 다시 열기 */
            recoveryTarget = currentAngle + DOOR_PINCH_RECOVERY_ANGLE_DEG;
        }
        else
        {
            /* 열리는 중 끼임 -> 다시 닫기 */
            recoveryTarget = currentAngle - DOOR_PINCH_RECOVERY_ANGLE_DEG;
        }

        recoveryTarget = clampFloat32(recoveryTarget,
                                      DOOR_MIN_ANGLE_DEG,
                                      DOOR_MAX_ANGLE_DEG);

        CurrentSensor_ClearFault(DOOR_MOTOR_ID);
        Door_Motor_SetTarget(recoveryTarget);
    }

    /* -------------------------------------------------
     * Window pinch
     * ------------------------------------------------- */
    if (windowFault == CURRENT_FAULT_MOTOR)
    {
        Window_Motor_Stop();
        CurrentSensor_StopSense(WINDOW_MOTOR_ID);

        can_send_PinchDetection(PINCH_TYPE_WINDOW);

        /* 버저 경고 */
        Buzzer_Request(BUZ_EVENT_PINCH);

        currentAngle = Window_Motor_GetCurrentAngle();

        if (g_rxWindowCmd == OPEN_CLOSE_CLOSE)
        {
            recoveryTarget = currentAngle + WINDOW_PINCH_RECOVERY_ANGLE_DEG;
        }
        else
        {
            recoveryTarget = currentAngle - WINDOW_PINCH_RECOVERY_ANGLE_DEG;
        }

        recoveryTarget = clampFloat32(recoveryTarget,
                                      WINDOW_MIN_ANGLE_DEG,
                                      WINDOW_MAX_ANGLE_DEG);

        CurrentSensor_ClearFault(WINDOW_MOTOR_ID);
        Window_Motor_SetTarget(recoveryTarget);
    }
}

void CurrentSensor_Task(uint8 motorId)
{
    CurrentSensorState *sensor = getCurrentSensor(motorId);
    IfxEvadc_Adc_Channel *channel = NULL;

    float32 FILTER_ALPHA;
    uint8 START_BLANK_COUNT;
    uint8 BASELINE_SAMPLES;
    float32 JAM_RAW_DIFF_TH;
    uint8 JAM_COUNT_TH;

    switch (motorId) {
        case DOOR_MOTOR_ID:
            channel = &g_curDoorChannel;

            FILTER_ALPHA = DOOR_FILTER_ALPHA;
            START_BLANK_COUNT = DOOR_START_BLANK_COUNT;
            BASELINE_SAMPLES = DOOR_BASELINE_SAMPLES;
            JAM_RAW_DIFF_TH = DOOR_JAM_RAW_DIFF_TH ;
            JAM_COUNT_TH = DOOR_JAM_COUNT_TH;
            break;

       case WINDOW_MOTOR_ID:
            channel = &g_curWindowChannel;

            FILTER_ALPHA = WINDOW_FILTER_ALPHA;
            START_BLANK_COUNT = WINDOW_START_BLANK_COUNT;
            BASELINE_SAMPLES = WINDOW_BASELINE_SAMPLES;
            JAM_RAW_DIFF_TH = WINDOW_JAM_RAW_DIFF_TH ;
            JAM_COUNT_TH = WINDOW_JAM_COUNT_TH;
            break;
    }

    Ifx_EVADC_G_RES result;
    uint16 raw;
    float32 rawF;

    if (sensor->senseActive == FALSE)
    {
        return;
    }

    if (sensor->faultLatched == TRUE)
    {
        return;
    }

    result = IfxEvadc_Adc_getResult(channel);

    if (result.B.VF != 1)
    {
        return;
    }

    raw = (uint16)result.B.RESULT;
    sensor->curRaw = raw;
    rawF = (float32)raw;

    sensor->curVolt = (rawF * CUR_REF_VOLTAGE) / CUR_ADC_MAX;
    sensor->curAmp  = Current_CalcAmp(sensor->curVolt, sensor->zeroVolt);

    if (sensor->curValid == FALSE)
    {
        sensor->filtRaw     = rawF;
        sensor->baseRaw     = rawF;
        sensor->diffRaw     = 0.0f;
        sensor->peakDiffRaw = 0.0f;
        sensor->jamCnt      = 0;
        sensor->spike       = FALSE;
        sensor->curValid    = TRUE;
        return;
    }

    sensor->filtRaw = (FILTER_ALPHA * rawF) +
                      ((1.0f - FILTER_ALPHA) * sensor->filtRaw);

    if (sensor->blankCnt < START_BLANK_COUNT)
    {
        sensor->blankCnt++;
        sensor->diffRaw = 0.0f;
        sensor->jamCnt = 0;
        return;
    }

    if (sensor->monitoring == FALSE)
    {
        sensor->baseRaw = ((sensor->baseRaw * (float32)sensor->baseCnt) + sensor->filtRaw) /
                          ((float32)sensor->baseCnt + 1.0f);

        if (sensor->baseCnt < BASELINE_SAMPLES)
        {
            sensor->baseCnt++;
            sensor->diffRaw = 0.0f;
            sensor->jamCnt = 0;
            return;
        }
        else
        {
            sensor->monitoring = TRUE;
            sensor->diffRaw = 0.0f;
            sensor->jamCnt = 0;
            return;
        }
    }

    sensor->diffRaw = fabsf(sensor->filtRaw - sensor->baseRaw);

    if (sensor->diffRaw > sensor->peakDiffRaw)
    {
        sensor->peakDiffRaw = sensor->diffRaw;
    }

    if (sensor->fault == CURRENT_FAULT_NONE)
    {
        if (sensor->diffRaw >= JAM_RAW_DIFF_TH)
        {
            if (sensor->jamCnt < 255)
            {
                sensor->jamCnt++;
            }
        }
        else
        {
            sensor->jamCnt = 0;
        }

        if (sensor->jamCnt >= JAM_COUNT_TH)
        {
            sensor->spike = TRUE;
            sensor->faultLatched = TRUE;
            sensor->fault = CURRENT_FAULT_MOTOR;
        }
    }
}

/************/

/* Current Sensor Init */

void initCurrentSensor(void)
{
    IfxEvadc_Adc_Group *group;
    IfxEvadc_Adc_ChannelConfig adcChannelConfig;

    group = EVADC_Group0_getHandle();

    /* AN1 */
    IfxEvadc_Adc_initChannelConfig(&adcChannelConfig, group);
    adcChannelConfig.channelId = DOOR_CHANNEL_ID;
    adcChannelConfig.resultRegister = DOOR_RESULT_REG;
    IfxEvadc_Adc_initChannel(&g_curDoorChannel, &adcChannelConfig);

    /* AN2 */
    IfxEvadc_Adc_initChannelConfig(&adcChannelConfig, group);
    adcChannelConfig.channelId = WINDOW_CHANNEL_ID;
    adcChannelConfig.resultRegister = WINDOW_RESULT_REG;
    IfxEvadc_Adc_initChannel(&g_curWindowChannel, &adcChannelConfig);

    /* queue */
    IfxEvadc_Adc_addToQueue(&g_curDoorChannel, IfxEvadc_RequestSource_queue0, IFXEVADC_QUEUE_REFILL);
    IfxEvadc_Adc_addToQueue(&g_curWindowChannel, IfxEvadc_RequestSource_queue0, IFXEVADC_QUEUE_REFILL);
}

/***************/

/* Current Sensor Library */
static CurrentSensorState* getCurrentSensor(uint8 motorId)
{
    switch (motorId) {
        case DOOR_MOTOR_ID:
            return &g_doorSensor;

        case WINDOW_MOTOR_ID:
            return &g_windowSensor;

        default:
            return NULL;
    }
}

static float32 Current_CalcAmp(float32 voltage, float32 zeroVolt)
{
    return (voltage - zeroVolt) / ACS_SENSITIVITY;
}

float32 CurrentSensor_GetAmp(uint8 motorId)
{
    CurrentSensorState *sensor = getCurrentSensor(motorId);

    return sensor->curAmp;
}

uint16 CurrentSensor_GetRaw(uint8 motorId)
{
    CurrentSensorState *sensor = getCurrentSensor(motorId);

    return sensor->curRaw;
}

CurrentFaultType CurrentSensor_GetFault(uint8 motorId)
{
    CurrentSensorState *sensor = getCurrentSensor(motorId);

    return sensor->fault;
}

void CurrentSensor_ClearFault(uint8 motorId)
{
    CurrentSensorState *sensor = getCurrentSensor(motorId);

    sensor->spike = FALSE;
    sensor->fault = CURRENT_FAULT_NONE;
    sensor->faultLatched = FALSE;
}

void CurrentSensor_StartSense(uint8 motorId)
{
    CurrentSensorState *sensor = getCurrentSensor(motorId);

    sensor->senseActive   = TRUE;
    sensor->monitoring    = FALSE;
    sensor->faultLatched  = FALSE;

    sensor->blankCnt      = 0;
    sensor->baseCnt       = 0;
    sensor->jamCnt        = 0;

    sensor->spike         = FALSE;
    sensor->fault         = CURRENT_FAULT_NONE;

    sensor->curValid      = FALSE;

    sensor->filtRaw       = 0.0f;
    sensor->baseRaw       = 0.0f;
    sensor->diffRaw       = 0.0f;
    sensor->peakDiffRaw   = 0.0f;
}

void CurrentSensor_StopSense(uint8 motorId)
{
    CurrentSensorState *sensor = getCurrentSensor(motorId);

    sensor->senseActive   = FALSE;
    sensor->monitoring    = FALSE;
    sensor->faultLatched  = FALSE;

    sensor->blankCnt      = 0;
    sensor->baseCnt       = 0;
    sensor->jamCnt        = 0;

    sensor->filtRaw       = 0.0f;
    sensor->baseRaw       = 0.0f;
    sensor->diffRaw       = 0.0f;
}
