/**********************************************************************************************************************
 * \file DFPlayer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "MCMCAN.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define DFPLAYER_PIN_RX             IfxAsclin1_RXA_P15_1_IN
#define DFPLAYER_PIN_TX             IfxAsclin1_TX_P15_0_OUT

#define DFPLAYER_BAUDRATE        9600
#define DFPLAYER_TX_BUFFER_SIZE  64
#define DFPLAYER_RX_BUFFER_SIZE  64

/* Definition of the interrupt priorities */
#define INTPRIO_ASCLIN1_RX      18
#define INTPRIO_ASCLIN1_TX      19

#define UART_RX_BUFFER_SIZE     64                                      /* Definition of the receive buffer size    */
#define UART_TX_BUFFER_SIZE     64                                      /* Definition of the transmit buffer size   */
#define SIZE                    13                                      /* Size of the string                       */

/* DFPlayer */
#define DFPLAYER_PORT     15
#define DFPLAYER_TX_PIN   0
#define DFPLAYER_RX_PIN   1

#define DFPLAYER_TX_PCx   (PCx_OUTPUT_ALT2)
#define DFPLAYER_RX_PCx   (PCx_INPUT_PUSHPULL)

#define DFPLAYER_SEND_LENGTH 10

/* DFPlayer UART Library */
#define Stack_Header 0
#define Stack_Version 1
#define Stack_Length 2
#define Stack_Command 3
#define Stack_ACK 4
#define Stack_Parameter 5
#define Stack_CheckSum 7
#define Stack_End 9

#define CMD_PLAY_FOLDER         0x0F
#define CMD_SET_VOLUME          0x06
#define CMD_RESET               0x0C
#define CMD_PLAY_FOLDER_LOOP    0x17

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Declaration of the ASC handle */
static IfxAsclin_Asc g_dfPlayerAsc;

/* Declaration of the FIFOs parameters */
static uint8 g_dfTxBuffer[DFPLAYER_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_dfRxBuffer[DFPLAYER_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

// SPEAKER
uint8 _sending[DFPLAYER_SEND_LENGTH] = {0x7E, 0xFF, 06, 00, 00, 00, 00, 00, 00, 0xEF};

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

void delayMs(uint32 ms);
void dfReset(void);
void dfSetVolume(uint8 vol);
void playDFPlayerMusic(uint8 folderNumber, uint8 fileNumber);
void playDFPlayerMusicLoop(uint8 folderNumber);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Interrupt Service Routines */
IFX_INTERRUPT(asclin1TxISR, 0, INTPRIO_ASCLIN1_TX);
void asclin1TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_dfPlayerAsc);
}

IFX_INTERRUPT(asclin1RxISR, 0, INTPRIO_ASCLIN1_RX);
void asclin1RxISR(void)
{
    IfxAsclin_Asc_isrReceive(&g_dfPlayerAsc);
}

/*****************/

/* DFPlayer Task */

void AudioControl_Task(void)
{
    static Ignition_t prevIgnition = IGNITION_OFF;

    // 시동 킬 떄
    if ((prevIgnition == IGNITION_OFF) &&
        (g_rxIgnitionState.ignition_state == IGNITION_ON))
    {
        playDFPlayerMusicLoop(g_rxCurrentUserId);
    }

    prevIgnition = g_rxIgnitionState.ignition_state;
}

/*****************/

/* DFPlayer Init */

/* This function initializes the ASCLIN UART module */
void init_ASCLIN_UART(void)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN1);

    /* Set the desired baud rate */
    ascConfig.baudrate.baudrate = DFPLAYER_BAUDRATE;

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN1_TX;
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN1_RX;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig.txBuffer = &g_dfTxBuffer;
    ascConfig.txBufferSize = DFPLAYER_TX_BUFFER_SIZE;
    ascConfig.rxBuffer = &g_dfRxBuffer;
    ascConfig.rxBufferSize = DFPLAYER_RX_BUFFER_SIZE;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR,           IfxPort_InputMode_pullUp,     /* CTS pin not used */
        &DFPLAYER_PIN_RX,   IfxPort_InputMode_pullUp,     /* RX pin           */
        NULL_PTR,           IfxPort_OutputMode_pushPull,  /* RTS pin not used */
        &DFPLAYER_PIN_TX,   IfxPort_OutputMode_pushPull,  /* TX pin           */
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_dfPlayerAsc, &ascConfig); /* Initialize module with above parameters */
}

void initDFPlayer(void)
{
    init_ASCLIN_UART();

    delayMs(1500);          // 최소 1~2초는 먼저 대기
    dfReset();
    delayMs(1500);          // reset 후 다시 대기
    dfSetVolume(5);
    delayMs(200);
}

/*************************/

/* DFPlayer UART Library */

void uint16ToArray(uint16 value, uint8 *array)
{
    *array = (uint8)(value>>8);
    *(array+1) = (uint8)(value);
}

uint16 calculateCheckSum(uint8 *buffer)
{
    uint16 sum = 0;
    for (int i=Stack_Version; i<Stack_CheckSum; i++) {
        sum += buffer[i];
    }
    return -sum;
}

void sendStack(void)
{
    Ifx_SizeT count = DFPLAYER_SEND_LENGTH;
    IfxAsclin_Asc_write(&g_dfPlayerAsc, _sending, &count, TIME_INFINITE);
}

void dfReset(void)
{
    _sending[Stack_Command]       = CMD_RESET;
    _sending[Stack_Parameter]     = 0x00;
    _sending[Stack_Parameter + 1] = 0x00;

    sendStack();
}

void dfSetVolume(uint8 vol)
{
    _sending[Stack_Command]       = CMD_SET_VOLUME;
    _sending[Stack_Parameter]     = 0x00;
    _sending[Stack_Parameter + 1] = vol;

    sendStack();
}

void playDFPlayerMusic(uint8 folderNumber, uint8 fileNumber)
{
    _sending[Stack_Command] = CMD_PLAY_FOLDER;

    // playFolder(folderNumber, fileNumber)
    _sending[Stack_Parameter]     = folderNumber;  // parameter high byte
    _sending[Stack_Parameter + 1] = fileNumber;    // parameter low byte

    uint16ToArray(calculateCheckSum(_sending), _sending + Stack_CheckSum);
    sendStack();
}

void playDFPlayerMusicLoop(uint8 folderNumber)
{
    _sending[Stack_Command]     = CMD_PLAY_FOLDER_LOOP;
    _sending[Stack_Parameter]   = folderNumber;

    sendStack();
}
