/**********************************************************************************************************************
 * \file EVADC_MANAGER.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxEvadc_Adc.h"
#include "EVADC_Manager.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/* EVADC handle */
static IfxEvadc_Adc g_evadc;
static IfxEvadc_Adc_Group g_adcGroup0;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void EVADC_Manager_initModule(void)
{
    IfxEvadc_Adc_Config adcConfig;

    IfxEvadc_Adc_initModuleConfig(&adcConfig, &MODULE_EVADC);
    IfxEvadc_Adc_initModule(&g_evadc, &adcConfig);
}

IfxEvadc_Adc* EVADC_Manager_getHandle(void)
{
    return &g_evadc;
}

IfxEvadc_Adc_Group* EVADC_Group0_getHandle(void)
{
    return &g_adcGroup0;
}

void EVADC_Group0_init(void)
{
    IfxEvadc_Adc *evadc;
    IfxEvadc_Adc_GroupConfig adcGroupConfig;

    evadc = EVADC_Manager_getHandle();

    IfxEvadc_Adc_initGroupConfig(&adcGroupConfig, evadc);

    adcGroupConfig.groupId = IfxEvadc_GroupId_0;
    adcGroupConfig.master = IfxEvadc_GroupId_0;
    adcGroupConfig.startupCalibration = TRUE;

    adcGroupConfig.arbiter.requestSlotQueue0Enabled = TRUE;
    adcGroupConfig.queueRequest[0].triggerConfig.gatingMode = IfxEvadc_GatingMode_always;

    IfxEvadc_Adc_initGroup(&g_adcGroup0, &adcGroupConfig);
}

void EVADC_Group0_start(void)
{
    IfxEvadc_Adc_startQueue(&g_adcGroup0, IfxEvadc_RequestSource_queue0);
}
