/**********************************************************************************************************************
 * \file FSR.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "FSR.h"
#include "IfxEvadc_Adc.h"
#include "EVADC_Manager.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* AN0 = Group0 Channel0 */
#define FSR_CHANNEL_ID      IfxEvadc_ChannelId_0
#define FSR_RESULT_REG      IfxEvadc_ChannelResult_0

/* 기준 전압: 배선에 맞게 수정 */
#define FSR_REF_VOLTAGE 5.0f    // 5V
#define FSR_ADC_MAX 4095.0f     //

#define FSR_RAW_MIN 2500.0f
#define FSR_RAW_MAX 3200.0f

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/* EVADC handle */
static IfxEvadc_Adc_Channel g_fsrChannel;

/* FSR values */
static volatile uint16  g_fsrRaw = 0;
static volatile float32 g_fsrVoltage = 0.0f;
static volatile uint8   g_fsrPercent = 0;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

static uint8 FSR_CalcPercent(uint16 raw);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Task */
void FSR_Task(void)
{
    Ifx_EVADC_G_RES result;

    /* 결과 읽기 */
    result = IfxEvadc_Adc_getResult(&g_fsrChannel);

    if (result.B.VF == 1)
    {
        g_fsrRaw = (uint16)result.B.RESULT;
        g_fsrVoltage = ((float32)g_fsrRaw * FSR_REF_VOLTAGE) / FSR_ADC_MAX;
        g_fsrPercent = FSR_CalcPercent(g_fsrRaw);
    }
}

/************/

/* FSR Init */

void initFSR(void)
{
    IfxEvadc_Adc_Group *group;
    IfxEvadc_Adc_ChannelConfig adcChannelConfig;

    group = EVADC_Group0_getHandle();

    IfxEvadc_Adc_initChannelConfig(&adcChannelConfig, group);
    adcChannelConfig.channelId = FSR_CHANNEL_ID;
    adcChannelConfig.resultRegister = FSR_RESULT_REG;

    IfxEvadc_Adc_initChannel(&g_fsrChannel, &adcChannelConfig);

    IfxEvadc_Adc_addToQueue(&g_fsrChannel, IfxEvadc_RequestSource_queue0, IFXEVADC_QUEUE_REFILL);
}

/***************/

/* FSR Library */
static uint8 FSR_CalcPercent(uint16 raw)
{
    float32 percent;

    percent = ((FSR_RAW_MAX - (float32)raw) /
              (FSR_RAW_MAX - FSR_RAW_MIN)) * 100.0f;

    if (percent < 0.0f) percent = 0.0f;
    if (percent > 100.0f) percent = 100.0f;

    return (uint8)(percent + 0.5f);
}

uint16 FSR_GetRaw(void)
{
    return g_fsrRaw;
}

float32 FSR_GetVoltage(void)
{
    return g_fsrVoltage;
}

uint8 FSR_GetPercent(void)
{
    return g_fsrPercent;
}
