/**********************************************************************************************************************
 * \file UltraSonic.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxGtm_Tim_In.h"
#include "IfxGtm_Tom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* Global */
#define PCn_3_IDX 27
#define PCn_6_IDX 19

#define PCx_NO_PULL         0x0
#define PCx_GENERAL_OUTPUT  0x10

/* UltraSonic */
#define ULTRASONIC_PORT 11
#define TRIG_PIN        6
#define ECHO_PIN        3

#define ULTRASONIC_POUT (P11_OUT)

#define ULTRASONIC_TRIG_PCx (PCx_GENERAL_OUTPUT)
#define ULTRASONIC_ECHO_PCx (PCx_NO_PULL)

#define ULTRASONIC_ECHO_TIM_IN   IfxGtm_TIM2_2_P11_3_IN

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Tim_In g_driverTIM;                              /* TIM driver structure                                     */
boolean g_dataCoherent = FALSE;                         /* Boolean to know if the measured data is coherent         */

typedef enum
{
    US_IDLE = 0,
    US_WAIT_ECHO,
    US_DONE
} UltrasonicState;

volatile UltrasonicState g_ultraState = US_IDLE;
volatile uint16 g_distanceCm = 0;
volatile boolean g_ultraReady = FALSE;
volatile boolean g_ultraTrigBusy = FALSE;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

uint32 getEchoTimeUs(void);
void Ultrasonic_TriggerOneShot(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* UltraSonic Task */

void Ultrasonic_Task(void)
{
    uint32 durationUs;
    static uint16 triggerIntervalCnt = 0;
    static uint16 echoWaitCnt = 0;

    switch(g_ultraState)
    {
        case US_IDLE:
            triggerIntervalCnt++;

            if(triggerIntervalCnt >= 50U)   // 1ms task 기준 50ms마다 측정 시작
            {
                triggerIntervalCnt = 0U;
                echoWaitCnt = 0U;

                Ultrasonic_TriggerOneShot();
                g_ultraState = US_WAIT_ECHO;
            }
            break;

        case US_WAIT_ECHO:
            echoWaitCnt++;
            durationUs = getEchoTimeUs();

            if(durationUs > 100U && durationUs < 30000U)
            {
                g_distanceCm = (uint16)(durationUs / 58U);
                g_ultraReady = TRUE;
                g_ultraState = US_DONE;
            }
            else if(echoWaitCnt >= 30U)   // 30ms timeout
            {
                g_ultraState = US_IDLE;
            }
            break;

        case US_DONE:
            g_ultraState = US_IDLE;
            break;

        default:
            g_ultraState = US_IDLE;
            break;
    }
}

/*******************/

/* UltraSonic Init */

/* This function initializes the TIM to capture a PWM signals */
void init_TIM(void)
{
    IfxGtm_enable(&MODULE_GTM);                                         /* Enable the GTM                           */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);        /* Enable the CMU clock 0                   */

    IfxGtm_Tim_In_Config configTIM;

    IfxGtm_Tim_In_initConfig(&configTIM, &MODULE_GTM);                  /* Initialize default parameters            */
    configTIM.filter.inputPin = &ULTRASONIC_ECHO_TIM_IN;                /* Select input port pin                    */
    configTIM.filter.inputPinMode = IfxPort_InputMode_noPullDevice;     /* Select input port pin mode               */
    IfxGtm_Tim_In_init(&g_driverTIM, &configTIM);                       /* Initialize the TIM                       */
}

void initUltraSonic(void)
{
    // Echo pin input
    P11_IOCR0.U &= ~(0x1F << PCn_3_IDX);
    P11_IOCR0.U |=  (ULTRASONIC_ECHO_PCx << PCn_3_IDX);

    // Trig pin output
    P11_IOCR4.U &= ~(0x1F << PCn_6_IDX);
    P11_IOCR4.U |=  (ULTRASONIC_TRIG_PCx << PCn_6_IDX);

    // Trig Low
    ULTRASONIC_POUT.U &= ~(1U << TRIG_PIN);

    init_TIM();
}

/*****************/

/* UltraSonic Library */

// read Echo Pulse Width
uint32 getEchoTimeUs(void)
{
    float32 period;
    float32 duty;
    float32 highTimeSec;

    IfxGtm_Tim_In_update(&g_driverTIM);                             // TIM 값 업데이트

    // High 시간 (sec)
    period = IfxGtm_Tim_In_getPeriodSecond(&g_driverTIM);
    duty   = IfxGtm_Tim_In_getDutyPercent(&g_driverTIM, &g_dataCoherent) / 100.0;
    highTimeSec = period * duty;

    return (uint32)(highTimeSec * 1000000);                         // us 변환
}


void Ultrasonic_TriggerStart(void)
{
    ULTRASONIC_POUT.U |= (1U << TRIG_PIN);
}

void Ultrasonic_TriggerStop(void)
{
    ULTRASONIC_POUT.U &= ~(1U << TRIG_PIN);
}

void Ultrasonic_TriggerOneShot(void)
{
    volatile uint32 i;

    if(g_ultraTrigBusy == TRUE)
    {
        return;
    }

    g_ultraTrigBusy = TRUE;

    /* TRIG High */
    ULTRASONIC_POUT.U |= (1U << TRIG_PIN);

    /* 약 10us 정도 delay - 보정 필요 */
    for(i = 0; i < 300; i++) __nop();

    /* TRIG Low */
    ULTRASONIC_POUT.U &= ~(1U << TRIG_PIN);

    g_ultraTrigBusy = FALSE;
}

void Ultrasonic_TriggerOneShotDone(void)
{
    Ultrasonic_TriggerStop();
    g_ultraTrigBusy = FALSE;
}
